import type { Locale } from "@/lib/i18n";
import type { TestCopy, TestSlug } from "@/lib/tests";

type LocalizedTestCopy = Record<TestSlug, TestCopy>;

const en = {
  guided: {
    name: "Guided Screen Test",
    shortName: "Guided test",
    seoTitle: "Guided Screen Test: Check Your Monitor Online",
    description: "Run a free guided screen test for dead pixels, backlight bleed, grayscale uniformity, banding, color, and motion in your browser.",
    intro: "Six quick checks. Mark what you notice, then get a plain-English summary.",
    duration: "About 2 minutes",
    preparation: [
      "Clean the panel first. A crumb is a convincing dead pixel.",
      "Use the brightness level you normally use.",
      "Enter fullscreen when you are ready to inspect the edges.",
    ],
    observations: [
      { signal: "A dot stays fixed through several colors", meaning: "It may be a dead pixel or a stuck subpixel." },
      { signal: "Gray areas look cloudy or tinted", meaning: "The panel may have a uniformity issue." },
      { signal: "A smooth shade breaks into visible stripes", meaning: "You may be seeing gradient banding." },
      { signal: "The moving target leaves a dark or bright trail", meaning: "The panel may show ghosting or overdrive overshoot." },
    ],
    limitation: "This is a visual browser check, not a colorimeter or laboratory measurement.",
    guideLabel: "Browse the screen testing guides",
  },
  "dead-pixel": {
    name: "Dead Pixel Test",
    shortName: "Dead pixels",
    seoTitle: "Dead Pixel Test: Check Your Screen Online",
    description: "Use full-screen white, black, red, green, and blue colors to find dead pixels and stuck subpixels without downloading an app.",
    intro: "Fill the screen with solid colors and look for a dot that refuses to change.",
    duration: "1-2 minutes",
    preparation: [
      "Wipe away dust and fingerprints before you begin.",
      "Sit at your normal viewing distance, then move closer for a second pass.",
      "Check every color because a stuck subpixel can hide on one background.",
    ],
    observations: [
      { signal: "A pixel stays black on every color", meaning: "It is likely a dead pixel that is no longer lighting up." },
      { signal: "A pixel stays red, green, blue, or white", meaning: "It is more likely a stuck subpixel than a fully dead pixel." },
      { signal: "The mark appears in a screenshot on another display", meaning: "The problem is in the rendered image or software, not this panel." },
    ],
    limitation: "A browser can reveal suspicious pixels, but it cannot confirm warranty eligibility or safely repair panel hardware.",
    guideLabel: "Read how to check dead pixels",
  },
  "backlight-bleed": {
    name: "Backlight Bleed Test",
    shortName: "Backlight bleed",
    seoTitle: "Backlight Bleed Test: Fullscreen Black Screen",
    description: "Open a full-screen black test in a dark room to check a monitor or laptop for bright edges, cloudy corners, and uneven backlighting.",
    intro: "Use a black screen in a dark room and check the edges for bright patches.",
    duration: "About 1 minute",
    preparation: [
      "Dim the room, but keep brightness at the level you actually use.",
      "Look straight at the panel from your normal seating position.",
      "Hide the controls so their light does not contaminate the test.",
    ],
    observations: [
      { signal: "A bright patch stays near an edge or corner", meaning: "It may be backlight bleed, especially if it stays put as you move." },
      { signal: "The glow changes when your head moves", meaning: "It may be viewing-angle glow rather than fixed backlight bleed." },
      { signal: "A phone photo looks worse than your eyes see", meaning: "Camera exposure can exaggerate glow. Judge the panel with your eyes first." },
    ],
    limitation: "This test helps you compare visible patches. Panel type, viewing angle, room light, and camera exposure can change the result.",
    guideLabel: "Read the backlight bleed guide",
  },
  grayscale: {
    name: "Grayscale and Uniformity Test",
    shortName: "Grayscale",
    seoTitle: "Screen Uniformity Test: Fullscreen Grayscale",
    description: "Check screen uniformity with full-screen 5%, 10%, 25%, 50%, 75%, and 100% grayscale patterns generated in your browser.",
    intro: "Move through gray levels and look for cloudy patches, tint, or dirty-screen effect.",
    duration: "1-2 minutes",
    preparation: [
      "Let the display warm up if it has just been switched on.",
      "Use your normal brightness and sit directly in front of the panel.",
      "Scan the center, edges, and corners at every gray level.",
    ],
    observations: [
      { signal: "Gray looks darker in cloudy patches", meaning: "This can indicate brightness uniformity variation or dirty-screen effect." },
      { signal: "One area shifts pink, green, or blue", meaning: "The panel may have tint uniformity variation." },
      { signal: "Only very dark gray looks uneven", meaning: "Near-black behavior varies by panel type and can improve after warm-up." },
    ],
    limitation: "Uniformity varies with viewing angle and panel technology. Compare what you see with your real use, not a camera alone.",
    guideLabel: "Read the screen uniformity guide",
  },
  gradient: {
    name: "Gradient Banding Test",
    shortName: "Gradient banding",
    seoTitle: "Gradient Test: Check Your Monitor for Banding",
    description: "Display smooth neutral, red, green, and blue gradients to check a monitor for visible banding, abrupt steps, and color transitions.",
    intro: "Inspect smooth gradients for sudden bands, blocks, or color jumps.",
    duration: "About 1 minute",
    preparation: [
      "Turn off unusual contrast or color-enhancement modes if possible.",
      "View both horizontal and vertical gradients.",
      "Check neutral first, then compare the red, green, and blue channels.",
    ],
    observations: [
      { signal: "A smooth ramp breaks into hard stripes", meaning: "You are seeing banding somewhere in the display or rendering pipeline." },
      { signal: "Banding appears in only one color channel", meaning: "A color setting or channel-specific panel behavior may be involved." },
      { signal: "The bands change after a display-mode change", meaning: "Bit depth, color range, or processing settings may be contributing." },
    ],
    limitation: "Browser color management, operating-system settings, bit depth, and panel processing can all affect a gradient.",
    guideLabel: "Browse the screen testing guides",
  },
  motion: {
    name: "Motion and Ghosting Test",
    shortName: "Motion",
    seoTitle: "Monitor Motion Test: Check Ghosting and Blur",
    description: "Run a browser-based moving-target test at several speeds to look for monitor ghosting, dark smearing, bright trails, and uneven motion.",
    intro: "Follow a moving target and check for trails, smearing, or uneven movement.",
    duration: "About 1 minute",
    preparation: [
      "Use the refresh rate and overdrive setting you normally use.",
      "Start at 240 px/s, then increase the speed.",
      "Keep your eyes on the moving target rather than the edge of the screen.",
    ],
    observations: [
      { signal: "A dark trail follows the target", meaning: "Slow pixel transitions may be creating visible smearing." },
      { signal: "A bright or inverted halo follows the target", meaning: "The display overdrive may be overshooting its target values." },
      { signal: "Movement jumps or pauses", meaning: "Browser load, frame pacing, or refresh-rate configuration may be involved." },
    ],
    limitation: "This browser test helps you see motion behavior. It is not a laboratory response-time measurement.",
    guideLabel: "Read the motion blur guide",
  },
  color: {
    name: "Monitor Color Test",
    shortName: "Color",
    seoTitle: "Monitor Color Test: Fullscreen RGB and CMY",
    description: "Show full-screen red, green, blue, cyan, magenta, yellow, black, and white colors to inspect pixels, tint, and color uniformity.",
    intro: "Show full-screen primary and secondary colors without image compression.",
    duration: "1-2 minutes",
    preparation: [
      "Disable blue-light or night modes if you want a neutral comparison.",
      "Use manual switching first. Automatic cycling is optional.",
      "Compare regions of one screen, not two uncalibrated devices as an exact match.",
    ],
    observations: [
      { signal: "A dot remains the wrong color", meaning: "A subpixel may be stuck or no longer responding." },
      { signal: "A solid color looks blotchy or tinted", meaning: "The panel may have color or brightness uniformity variation." },
      { signal: "Two displays show different colors", meaning: "Different presets and calibration can cause this even when both panels work." },
    ],
    limitation: "Solid colors reveal visual differences, but they do not calibrate a display or measure color accuracy.",
    guideLabel: "Browse the screen testing guides",
  },
} as const satisfies LocalizedTestCopy;

const zh = {
  guided: {
    name: "引导式屏幕测试",
    shortName: "引导测试",
    seoTitle: "引导式屏幕测试：在线检查显示器",
    description: "在浏览器中免费检查坏点、漏光、灰阶均匀性、渐变色带、色彩和动态拖影。",
    intro: "6 项快速检查。记下你看到的现象，最后得到一段清楚的结果。",
    duration: "大约 2 分钟",
    preparation: ["先清洁面板，一粒碎屑就很像坏点。", "使用你平时的屏幕亮度。", "准备检查边缘时再进入全屏。"],
    observations: [
      { signal: "一个小点在多种颜色下都固定不变", meaning: "它可能是坏点，或卡住的子像素。" },
      { signal: "灰色区域发花或偏色", meaning: "面板可能存在均匀性问题。" },
      { signal: "平滑色调断成明显条纹", meaning: "你看到的可能是渐变色带。" },
      { signal: "移动目标留下暗色或亮色轨迹", meaning: "面板可能出现拖影或过驱过冲。" },
    ],
    limitation: "这是浏览器目视检查，不是色度计或实验室测量。",
    guideLabel: "浏览英文屏幕测试指南",
  },
  "dead-pixel": {
    name: "坏点测试",
    shortName: "坏点",
    seoTitle: "坏点测试：在线检查屏幕坏点",
    description: "用全屏白、黑、红、绿、蓝纯色检查坏点和卡住的子像素，无需下载应用。",
    intro: "让屏幕依次显示纯色，寻找那个怎么都不变的小点。",
    duration: "1-2 分钟",
    preparation: ["开始前擦掉灰尘和指纹。", "先在日常观看距离检查，再靠近看一遍。", "每种颜色都要检查，卡住的子像素可能藏在某种背景里。"],
    observations: [
      { signal: "一个像素在所有颜色下都保持黑色", meaning: "它很可能是不再发光的坏点。" },
      { signal: "一个像素始终显示红、绿、蓝或白色", meaning: "它更像是卡住的子像素，而不是完全坏掉的像素。" },
      { signal: "截图放到另一块屏幕上仍能看到这个痕迹", meaning: "问题来自图像或软件，不是当前面板。" },
    ],
    limitation: "浏览器能暴露可疑像素，但无法判断保修资格，也不能安全修复面板硬件。",
    guideLabel: "阅读英文坏点检查指南",
  },
  "backlight-bleed": {
    name: "漏光测试",
    shortName: "漏光",
    seoTitle: "漏光测试：全屏纯黑检查",
    description: "在暗室中打开全屏纯黑图案，检查显示器或笔记本的亮边、云状亮斑和背光不均。",
    intro: "在暗室里显示纯黑画面，检查边缘有没有固定亮斑。",
    duration: "大约 1 分钟",
    preparation: ["调暗房间，但保持你实际使用的屏幕亮度。", "坐在日常位置，正对面板观察。", "隐藏控制栏，避免它的亮光干扰测试。"],
    observations: [
      { signal: "亮斑固定在边缘或角落", meaning: "这可能是漏光，尤其是你移动视角后它仍固定不变时。" },
      { signal: "头部移动时，亮光也跟着变化", meaning: "这可能是视角泛光，而不是固定漏光。" },
      { signal: "手机照片比肉眼看到的严重", meaning: "相机曝光会夸大亮光。先相信现场肉眼观察。" },
    ],
    limitation: "这项测试帮助你比较可见亮斑。面板类型、视角、环境光和相机曝光都会影响结果。",
    guideLabel: "阅读英文漏光检查指南",
  },
  grayscale: {
    name: "灰阶与均匀性测试",
    shortName: "灰阶",
    seoTitle: "屏幕均匀性测试：全屏灰阶检查",
    description: "在浏览器中显示 5%、10%、25%、50%、75% 和 100% 全屏灰阶，检查屏幕均匀性。",
    intro: "切换不同灰阶，检查云状斑块、偏色和脏屏效应。",
    duration: "1-2 分钟",
    preparation: ["如果显示器刚开机，先让它预热一会儿。", "使用日常亮度，并坐在面板正前方。", "在每个灰阶下检查中心、边缘和四角。"],
    observations: [
      { signal: "灰色区域出现较暗的云状斑块", meaning: "这可能是亮度均匀性差异或脏屏效应。" },
      { signal: "某个区域偏粉、偏绿或偏蓝", meaning: "面板可能存在色调均匀性差异。" },
      { signal: "只有很暗的灰阶看起来不均匀", meaning: "近黑表现因面板类型而异，预热后可能改善。" },
    ],
    limitation: "均匀性会随视角和面板技术变化。用真实使用场景判断，不要只看相机照片。",
    guideLabel: "阅读英文屏幕均匀性指南",
  },
  gradient: {
    name: "渐变色带测试",
    shortName: "渐变色带",
    seoTitle: "渐变测试：检查显示器色带",
    description: "显示平滑的中性、红、绿、蓝渐变，检查明显色带、突兀断层和颜色跳变。",
    intro: "检查平滑渐变里有没有突然出现的条带、色块或颜色跳变。",
    duration: "大约 1 分钟",
    preparation: ["如果可以，关闭不常用的对比度或色彩增强模式。", "水平和垂直渐变都要查看。", "先检查中性渐变，再比较红、绿、蓝通道。"],
    observations: [
      { signal: "平滑渐变断成明显条纹", meaning: "显示或渲染链路中的某个环节出现了色带。" },
      { signal: "色带只出现在一个颜色通道", meaning: "可能与色彩设置或特定通道的面板表现有关。" },
      { signal: "切换显示模式后色带发生变化", meaning: "位深、色彩范围或图像处理设置可能参与其中。" },
    ],
    limitation: "浏览器色彩管理、操作系统设置、位深和面板处理都会影响渐变。",
    guideLabel: "浏览英文屏幕测试指南",
  },
  motion: {
    name: "动态与拖影测试",
    shortName: "动态",
    seoTitle: "显示器动态测试：检查拖影和模糊",
    description: "用多档速度运行移动目标，观察显示器拖影、暗色涂抹、亮色轨迹和运动不均。",
    intro: "跟随移动目标，检查拖影、涂抹或不均匀运动。",
    duration: "大约 1 分钟",
    preparation: ["使用你平时的刷新率和过驱设置。", "从 240 像素/秒开始，再提高速度。", "视线跟随移动目标，不要盯着屏幕边缘。"],
    observations: [
      { signal: "目标后方出现暗色轨迹", meaning: "像素转换较慢，可能形成可见涂抹。" },
      { signal: "目标后方出现亮色或反色光晕", meaning: "显示器过驱可能发生过冲。" },
      { signal: "运动出现跳动或停顿", meaning: "可能与浏览器负载、帧时间或刷新率配置有关。" },
    ],
    limitation: "这项浏览器测试帮助你观察动态表现，但不是实验室响应时间测量。",
    guideLabel: "阅读英文动态模糊指南",
  },
  color: {
    name: "显示器色彩测试",
    shortName: "色彩",
    seoTitle: "显示器色彩测试：全屏 RGB 与 CMY",
    description: "显示全屏红、绿、蓝、青、品红、黄、黑、白纯色，检查像素、偏色和色彩均匀性。",
    intro: "不经过图片压缩，直接显示全屏三原色和二次色。",
    duration: "1-2 分钟",
    preparation: ["如果要进行中性比较，请关闭护眼或夜间模式。", "先手动切换，自动循环只是可选项。", "比较同一块屏幕的不同区域，不要把两台未校准设备当作精确基准。"],
    observations: [
      { signal: "一个小点始终显示错误颜色", meaning: "某个子像素可能卡住或已经失效。" },
      { signal: "纯色看起来发花或偏色", meaning: "面板可能存在色彩或亮度均匀性差异。" },
      { signal: "两块屏幕显示不同颜色", meaning: "不同预设和校准会造成差异，即使两块面板都正常工作。" },
    ],
    limitation: "纯色可以暴露视觉差异，但不能校准显示器或测量色彩准确度。",
    guideLabel: "浏览英文屏幕测试指南",
  },
} as const satisfies LocalizedTestCopy;

export const TEST_COPY = { en, zh } as const satisfies Record<Locale, LocalizedTestCopy>;
